# Site settings
title: UNESCO Chair in Urban Landscape
year: 2024
description: >- # this means to ignore newlines until "baseurl:"
  This is the official website for the UNESCO Chair in Urban Landscape at the University of Montreal, focusing on sustainable urbanization.
baseurl:
url: https://unesco-studio.umontreal.ca
contact:
  office: Office 4116
  email: shin.koseki@umontreal.ca
  phone: +1 (514) 343-2320
  mailing: Université de Montréal<br>Pavillon de la faculté de l’aménagement<br>CP 6128 Downtown Station<br>Montréal (Québec) H3C 3J7
  civic: UNESCO Chair in Urban Landscape<br>2940, Côte-Ste-Catherine Rd.<br>Offices 4112–4133<br>Montréal
  google_maps: https://maps.app.goo.gl/vx6kjg8gcna9SkAD9
social:
  linkedin: https://www.linkedin.com/company/unesco.studio/
  facebook: https://www.facebook.com/unesco.studio
  instagram: https://www.instagram.com/unesco.studio/
  tiktok: https://www.tiktok.com/@unesco.studio
usernames:
  linkedin: unesco.studio
  facebook: unesco.studio
  instagram: unesco.studio
  tiktok: unesco.studio

# Build settings
markdown: kramdown
theme: minima # or another theme if you've chosen one
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list as needed.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optional features
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Localization settings (for future multilingual support)
languages: ["en", "fr"]

# Custom variables
# You can define any number of custom variables here and access them throughout
# your site. For example:
color_palette: 
  - "#0d56fb"
  - "#c7cde8"
  - "#ba6528"
  - "#cdb9a3"
  - "#5dc928"
  - "#c0dfae"
  - "#fced00"
  - "#fff9ae"
  - "#ed145b"
  - "#f9a3be"
  - "#737373"
  - "#d1d3d4"

# Collections
collections:
  projects:
    output: true
  posts:
    output: true
  teachings:
    output: true
  team:
    output: true